### ISSUE TITLE
JS coding in 2.1.0 when first test fails

### ISSUE THREAD

**Issue by vobu** [karma-runner/karma-qunit#115]
JS runtime throws 
`TypeError: testResult.errors is undefined\nat node_modules/karma-qunit/lib/adapter.js:99`
when first test fails.

relevant src code snippet is
~~~
runner.log(function (details) {
      if (!details.result) {
        
// ...
        testResult.success = false
        testResult.errors.push(msg) // <- the array.push fails
      }
    })
~~~

Environment:
karma-qunit 2.1.0
karma 3.1.1
qUnit 2.6.1
node 11.1.0
macOS 10.14.2

**=> I will provide a PR fixing this!**

**Comment by Krinkle** [comment]
@volu in order to avoid reintroducing this bug second time in the future, it'd be great if you could provide some minimal steps to reproduce this issue.
