### ISSUE TITLE
DOM-elements isn't injected

### ISSUE THREAD

**Issue by SimenB** [karma-runner/karma-qunit#18]
Hi!

I'm probably doing something wrong, but I can't seem to get this working.

I have a few tests using the QUnit DOM-elements. But when using the karma to run the tests they aren't there.

``` html
<div id="qunit-fixture"></div>
```

Source: http://qunitjs.com/, http://qunitjs.com/intro/#testing-the-dom-manipulation

Is there some way to inject them, and empty/remove them between each test?

**Comment by asapach** [comment]
I'm doing this in one of my test files and it seems to work for me:

```js
QUnit.begin(function () {
	$('body').append('<div id="qunit-fixture"></div>');
});

QUnit.done(function () {
	$('#qunit-fixture').remove();
});
```
