### ISSUE TITLE
Karma Runner is deprecated

### ISSUE THREAD

**Issue by mauriciolauffer** [karma-runner/karma-qunit#183]
As KarmaJS had been [deprecated](https://github.com/karma-runner/karma?tab=readme-ov-file#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes), I've created a drop-in replacement with WebdriverIO: [WDIO QUnit Service](https://webdriver.io/docs/wdio-qunit-service/)

Hope it helps others using karma-qunit.

**Comment by Krinkle** [comment]
Thanks! I've added a mention of wdio-qunit-service at https://qunitjs.com/intro/#integrations (ref https://github.com/qunitjs/qunitjs.com/commit/b7f6be69d897ab7592c557ba0175f1d7d6584bbc).
