### ISSUE TITLE
Autostart from adapter conflicts with autostart from user 

### ISSUE THREAD

**Issue by Krinkle** [karma-runner/karma-qunit#27]
I've recently changed my test suite from loading synchronous to loading asynchronous (as a side-effect of a wider change in the delivery application).

As a result, the karma-qunit test is now broken because it has its own asynchronous startup that overrides the one provided by the user.

Both code paths set `QUnit.config.autostart = false;` and Karma's calls `.start()` when it is finished, but at that point the user code has only just begun to load and as such QUnit starts the test and also immediately ends the test (as there are 0 pending tests) and Karma shuts down the browser – before any of the tests were run.

```
INFO [launcher]: Starting browser Chrome
INFO [Chrome 44.0.2403 (Mac OS X 10.10.4)]: Connected on socket BbFAo6lyMsra5CMr3ukt with id 75541682
Chrome 44.0.2403 (Mac OS X 10.10.4): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
```

**Comment by shaikhimran786** [comment]
I am also facing same issue, anybody is having  solution or fix for this issue please share us.

**Comment by S4NT14G0** [comment]
Any update on this issue?

**Comment by diegodossantos95** [comment]
I am facing the same issue, someone can help me?

**Comment by vobujs** [comment]
+1
