### ISSUE TITLE
Possible regression on `0.1.5`

### ISSUE THREAD

**Issue by paulfalgout** [karma-runner/karma-qunit#28]
I'm not at all sure why this is occurring, but tests on backbone started failing with `0.1.4`
https://travis-ci.org/jashkenas/backbone/builds/72909935

But going back a version, they're fine.

https://github.com/jashkenas/backbone/pull/3742

I haven't had much opportunity to investigate further.

**Comment by paulfalgout** [comment]
@jridgewell solved it in the xref'd PR.

**Comment by Dignifiedquire** [comment]
@paulfalgout is this all good now, or do you need something from this side to be fixed?

**Comment by megawac** [comment]
We fixed it on the backbone end but it seems like it was a regression

**Comment by paulfalgout** [comment]
Well https://github.com/karma-runner/karma-qunit/pull/22 was blowing away our fixture in subsequent tests.  It looks like it was a breaking change made intentionally?

**Comment by Dignifiedquire** [comment]
@paulfalgout yes, but I did not take into account that this is a breaking change, will do some release magic and go to 0.2.0 for the breaking change

**Comment by dignifiedquire** [comment]
never got to this sorry, closing as I doubt this is still an issue
