### ISSUE TITLE
QUnit 2.0.0 Support

### ISSUE THREAD

**Issue by bworsfold** [karma-runner/karma-qunit#43]
I've tried to install qunitjs 2.0.0 using npm 3.0 to take advantage of the new before and after hooks.  However, when trying to do the install I get karma-qunit dependency errors.

Can you confirm qunitjs is compatible with qunitjs 2.0.0 while using NPM version 3.x? 

Looking at the karma-qunit package.json, it shows that it does support it, but then there is a peerDependency for ^1.14.

```
C:\projects\loct\loct\loct-war>npm install qunitjs@2.0.0 --savedev
loct@1.0.0 C:\projects\loct\loct\loct-war
`-- UNMET PEER DEPENDENCY qunitjs@2.0.0

npm WARN karma-qunit@1.1.0 requires a peer of qunitjs@^1.14.0 but none was installed.
npm WARN loct@1.0.0 No repository field.
npm ERR! code 1

C:\projects\loct\loct\loct-war>npm install
npm WARN karma-qunit@1.1.0 requires a peer of qunitjs@^1.14.0 but none was installed.
npm WARN loct@1.0.0 No repository field.

C:\projects\loct\loct\loct-war>npm list
loct@1.0.0 C:\projects\loct\loct\loct-war
+-- karma-qunit@1.1.0 extraneous
`-- UNMET PEER DEPENDENCY qunitjs@2.0.0 extraneous

npm ERR! peer dep missing: qunitjs@^1.14.0, required by karma-qunit@1.1.0
npm ERR! extraneous: karma-qunit@1.1.0 C:\projects\loct\loct\loct-war\node_modules\karma-qunit
```

Thanks,

Brad

**Comment by soswow** [comment]
Seems like there is PR already #42 but it's not moving atm

**Comment by masubi** [comment]
I've added some minor fixes for unit test:  #44 - hopefully, I did this correctly

**Comment by SublimeVincentHerl** [comment]
The same problem persist 
```
+-- karma-qunit@1.2.1 
`-- UNMET PEER DEPENDENCY qunitjs@^1.14.0 || ^2.0.0

npm WARN karma-qunit@1.2.1 requires a peer of qunitjs@^1.14.0 || ^2.0.0 but none was installed.
```

**Comment by dignifiedquire** [comment]
@SublimeVincentHerl what problem do you mean? with npm@3 you need to manually install a peer dependency, i.e. `npm --save-dev qunitjs`

**Comment by dignifiedquire** [comment]
Should be fixed in the latest release.
