### ISSUE TITLE
Never ending loop when `singlerun: false` and failing test

### ISSUE THREAD

**Issue by brunoscopelliti** [karma-runner/karma-qunit#47]
Hi,

I'm having an issue that I think is dued to `karma-qunit`.

I created a repo that describes the issue, and you could clone in order to reproduce yourself the problem: [karma-qunit-adapter-issue-47](https://github.com/brunoscopelliti/karma-qunit-adapter-issue-47).

In a few words:

I use karma, with qunit as testing framework... so I have also installed `karma-qunit` adapter.

When run the test with `singleRun: false` and there's at least a failing test, the adapter enters in a never ending loop in which it continues to log the exception ([view image](https://github.com/brunoscopelliti/karma-qunit-adapter-issue-47/blob/master/better-than-thousands-words.png)).

I am not expert about QUnit internals, however I noticed that when a test fails, QUnit creates an internal test that it uses somehow to track the failing test... karma-qunit executes the testDone callback even for this fake (or better internal) test. I don't know if this is wanted, or necessary, but it seem to be the cause of the never ending log stream.

Do you have any suggestion?

ps. I am using the latest version of all the packages involved (`karma`, `qunitjs`, `karma-qunit`).

**Comment by yt-scopelliti** [comment]
I am continuing investigation my issue...
It was introduced with `karma@1.0.0`; indeed using the following dependencies the demo works as expected.

```
"karma": "0.13.22",
"karma-chrome-launcher": "2.0.0",
"karma-qunit": "1.2.0",
"qunitjs": "2.0.1"
```

I'm not sure this is an issue with `karma`, or `karma-qunit`.

**Comment by brunoscopelliti** [comment]
I am continuing investigation my issue...
It was introduced with `karma@1.0.0;` indeed using the following dependencies the demo works as expected.

```
"karma": "0.13.22",
"karma-chrome-launcher": "2.0.0",
"karma-qunit": "1.2.0",
"qunitjs": "2.0.1"
```


I'm not sure this is an issue with karma, or karma-qunit.

**Comment by masubi** [comment]
@brunoscopelliti - i think you're analysis above is correct.  It looks like tc.result(result) causes https://github.com/karma-runner/karma-qunit/blob/master/src/adapter.js#L106 to eventually throw global failure error in karma debug.js which qunit then tries to log as an error thereby getting into infinite loop.  Here's a proposed fix for adapter:  https://github.com/karma-runner/karma-qunit/pull/48.  Open to better idea other than trying to fix this in karma's debug.js

**Comment by dignifiedquire** [comment]
Thanks @masubi I merged the PR for now, if a better solution comes around we can change it

**Comment by masubi** [comment]
@dignifiedquire - added a slight more robust check of the 'global failures' string in the description.  https://github.com/karma-runner/karma-qunit/pull/49

**Comment by brunoscopelliti** [comment]
@dignifiedquire , @masubi 

Thank you for this fix... I just noted it wasn't released on npm yet; any particular reason?

**Comment by dignifiedquire** [comment]
just released :)
