### ISSUE TITLE
karma-qunit doesn't display failing values

### ISSUE THREAD

**Issue by codinguncut** [karma-runner/karma-qunit#7]
karma-qunit does not display failing values for example when using "equal()"

<pre>
test('int check', function() {
  equal(1, 2, 'unequal ints');
});
</pre>

results in:

<pre>
Firefox 23.0.0 (Ubuntu) crypto int check FAILED
	unequal ints
	@/home/jonas/workspace/shufu/spec/test.js:79
	Test.prototype.run@/usr/local/lib/node_modules/karma-qunit/lib/qunit.js:136
	Test.prototype.queue/run/&lt;@/usr/local/lib/node_modules/karma-qunit/lib/qunit.js:279
	process@/usr/local/lib/node_modules/karma-qunit/lib/qunit.js:1277
	QUnit.start/&lt;@/usr/local/lib/node_modules/karma-qunit/lib/qunit.js:383
</pre>

This is considerable less useful than QUnit's own output:

<pre>
unequal ints
Expected: 	2
Result: 	1
Diff: 	2 1 
Source: 	@file:///home/jonas/workspace/shufu/spec/test.js:79
</pre>

I am running karma 0.10.2 and karma-qunit that I installed yesterday via npm.

**Comment by Krinkle** [comment]
Fixed by 264e4ccb3. See also #24.
