### ISSUE TITLE
"Adapter did not report total number of specs" error

### ISSUE THREAD

**Issue by lazd** [karma-runner/karma-qunit#8]
karma-qunit wants to report the total number of specs on complete, but Karma expects to have this information immediately after the first test is ran. This results in a warning when tests are ran:

```
WARN [PhantomJS 1.9.7 (Mac OS X)]: Adapter did not report total number of specs.
```

A workaround is to just tell Karma there are 0 tests, which avoids the warning, but results in "2 of 0 executed" messages.

qunit does not have a mechanism that can provide the total number of tests upfront, so it's not possible to give Karma what it wants. See https://github.com/jquery/qunit/issues/350

**Comment by Krinkle** [comment]
@dignifiedquire This can be closed now :)

**Comment by Daddelbob** [comment]
I am experiencing this behaviour, too. My tests don't run at all.
```
WARN [Chrome 72.0.3626 (Windows 7.0.0)]: Adapter did not report total number of specs.
Chrome 72.0.3626 (Windows 7.0.0): Executed 1 of null SUCCESS
```
    "@angular/cli": "^7.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",

**Comment by Krinkle** [comment]
@Daddelbob It looks like you're using Jasmine, not QUnit. The previous comments indicate that the issue was fixed for karma-qunit. Can you reproduce the issue with the latest versions of karma-qunit and qunit?

**Comment by Daddelbob** [comment]
@Krinkle Yes, I am using Jasmin and I could actually fix my Problem. Seems my PC is too weak to handle everything so I tried 
`ng test --source-map=false`
as suggested in https://github.com/karma-runner/karma/issues/3267#issuecomment-467092823
And my tests finally run again.
