### ISSUE TITLE
Support the new package name for `QUnit` (after version `2.4.1`)

### ISSUE THREAD

**Issue by BrandonOCasey** [karma-runner/karma-qunit#98]
The `qunitjs` package is being renamed to `qunitjs` after version `2.4.1` as per the warning when you install the newest version of `qunitjs`. Right now `karma-qunit` only knows to look for `qunitjs` and not `qunit` and will not work with newer versions.

**Comment by asapach** [comment]
For reference: https://github.com/qunitjs/qunit/pull/1232

**Comment by asapach** [comment]
More details:
>npm WARN deprecated qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.

**Comment by Johann-S** [comment]
@dignifiedquire do you plan on updating your karma plugin ?
